name: "Build"

on:
  workflow_call:
    inputs:
      upload:
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t test --parallel=3 --configuration=ci
      - run: npx nx affected -t build --parallel=3

      - name: "Upload artifact"
        if: ${{ inputs.upload == true }}
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: ./dist/apps/blow-it
